CONFIG_NAME: 'VGG19'
DATASET_NAME: SVHN
SEED: 1234

# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train'
  DATASET_EXTRA: True
  VALID_SPLIT: 0.8
  SAMPLE_SIZE: -1 # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  BATCH_SIZE: 32
  NUM_EPOCHS: 500
  NUM_HYPER_LOOP: 25
  LR: [0.0001, 0.1]      # Lists are optimized using skopt
  L2: [0.0001, 0.1]      #
  DROPOUT: [0.5, 0.9]    #
  MOM: [0.0, 0.5]        #
  SCHEDULER_PATIENCE: 10
  EARLY_STOPPING_PATIENCE: 25
