CONFIG_NAME: 'VGG19'
DATASET_NAME: SVHN
SEED: 1234

# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train'
  VALID_SPLIT: 0.8
  SAMPLE_SIZE: -1 # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  BATCH_SIZE: 256
  NUM_EPOCHS: 100
  NUM_HYPER_LOOP: 5
  LR: [0.001, 0.01]    # Lists are optimized using skopt
  L2: [0.0001, 0.001]  #
  DROPOUT: [0.0, 0.2]  #
  MOM: [0.75, 0.99]    #
  SCHEDULER_PATIENCE: 2
  EARLY_STOPPING_PATIENCE: 5
