CONFIG_NAME: 'DeepConv'
DATASET_NAME: SVHN
SEED: 1234

# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train'
  VALID_SPLIT: 0.8
  SAMPLE_SIZE: -1 # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  BATCH_SIZE: 32
  NUM_EPOCHS: 500
  LR: [0.001] # As list for simple grid search
  L2: [0.01] # Idem
  DROPOUT: [0.5] # Idem
  MOM: 0.9
  SCHEDULER_PATIENCE: 10
  EARLY_STOPPING_PATIENCE: 25